version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: agritrace-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: agritrace
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - agritrace-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agritrace-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongodb:27017/agritrace?authSource=admin
      - PORT=3000
      - JWT_SECRET=your-secret-key
      - JWT_EXPIRES_IN=24h
      - FABRIC_CHANNEL_NAME=mychannel
      - FABRIC_CHAINCODE_NAME=agritrace
      - FABRIC_MSP_ID=ProducersMSP
      - FABRIC_WALLET_PATH=./wallet
      - FABRIC_CONNECTION_PROFILE_PATH=./connection-profile.json
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - agritrace-network

volumes:
  mongodb_data:

networks:
  agritrace-network:
    name: agritrace-network
    driver: bridge 