version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  agritrace:
    external: true
    name: agritrace_default

services:
  explorerdb:
    image: ghcr.io/hyperledger-labs/explorer-db:latest
    container_name: explorerdb
    hostname: explorerdb
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - agritrace

  explorer:
    image: ghcr.io/hyperledger-labs/explorer:latest
    container_name: explorer
    hostname: explorer
    environment:
      - DATABASE_HOST=explorerdb
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ${PWD}/config.json:/opt/explorer/app/platform/fabric/config.json
      - ${PWD}/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ${PWD}/../blockchain/network/crypto-config:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - 8090:8080
    depends_on:
      explorerdb:
        condition: service_healthy
    networks:
      - agritrace 